package initdemo

import (
	"fmt"
	"os"
	"path/filepath"

	"kube-manifest-risk-scanner/internal/parser"
	"kube-manifest-risk-scanner/internal/report"
	"kube-manifest-risk-scanner/internal/scanner"
)

func Create(output string, force bool) error {
	if info, err := os.Stat(output); err == nil {
		if !force {
			if info.IsDir() {
				return fmt.Errorf("output directory already exists: %s (use --force to overwrite)", output)
			}
			return fmt.Errorf("output path already exists: %s (use --force to overwrite)", output)
		}
		if err := os.RemoveAll(output); err != nil {
			return fmt.Errorf("remove existing output %s: %w", output, err)
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("check output %s: %w", output, err)
	}

	manifestDir := filepath.Join(output, "manifests")
	if err := os.MkdirAll(manifestDir, 0755); err != nil {
		return fmt.Errorf("create demo manifests directory: %w", err)
	}

	files := map[string]string{
		filepath.Join(output, "README.md"):                  DemoREADME,
		filepath.Join(manifestDir, "good-deployment.yaml"):  GoodDeployment,
		filepath.Join(manifestDir, "risky-deployment.yaml"): RiskyDeployment,
		filepath.Join(manifestDir, "risky-service.yaml"):    RiskyService,
		filepath.Join(manifestDir, "risky-cronjob.yaml"):    RiskyCronJob,
	}
	for path, content := range files {
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}

	resources, scannedFiles, err := parser.ParseDir(manifestDir)
	if err != nil {
		return err
	}
	scanReport := scanner.Scan(resources, scannedFiles, scanner.Options{
		Profile:     "production",
		IncludeInfo: true,
	})
	rendered, err := report.Render(scanReport, "markdown")
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(output, "report.md"), []byte(rendered), 0644); err != nil {
		return fmt.Errorf("write sample report: %w", err)
	}
	return nil
}

const DemoREADME = `# Kube Risk Demo

This directory was generated by ` + "`kube-risk-scan init`" + `.

## Included Files

- ` + "`manifests/good-deployment.yaml`" + `: a small deployment with explicit namespace, replicas, probes, resources, and security context.
- ` + "`manifests/risky-deployment.yaml`" + `: intentionally risky settings such as privileged mode, host networking, hostPath, mutable images, and missing probes.
- ` + "`manifests/risky-service.yaml`" + `: a LoadBalancer service in the default namespace.
- ` + "`manifests/risky-cronjob.yaml`" + `: a CronJob with missing scheduling safeguards and an unpinned image.
- ` + "`report.md`" + `: a generated markdown report from the demo manifests.

## Run a Scan

` + "```sh" + `
kube-risk-scan scan --dir ./manifests --profile production
kube-risk-scan scan --dir ./manifests --profile production --format markdown --output report.md --include-info
` + "```" + `

The risky manifests produce findings because they model common pre-deployment mistakes: floating image tags, missing resource requests and limits, missing health probes, broad Linux capabilities, host namespace access, and externally exposed services.

Open ` + "`report.md`" + ` to view the generated markdown report. Customize any manifest and rerun the scan to see how the findings change.
`

const GoodDeployment = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: api
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: nginx:1.27.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
`

const RiskyDeployment = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: risky-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risky-api
  template:
    metadata:
      labels:
        app: risky-api
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      hostNetwork: true
      volumes:
        - name: host-root
          hostPath:
            path: /
      containers:
        - name: api
          image: nginx:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          volumeMounts:
            - name: host-root
              mountPath: /host
`

const RiskyService = `apiVersion: v1
kind: Service
metadata:
  name: risky-api
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: risky-api
  ports:
    - port: 80
      targetPort: 8080
`

const RiskyCronJob = `apiVersion: batch/v1
kind: CronJob
metadata:
  name: risky-cleanup
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          hostPID: true
          containers:
            - name: cleanup
              image: busybox
              command: ["sh", "-c", "echo cleanup"]
`
